### ISSUE TITLE
loading secrets

### ISSUE THREAD

**Issue by mikeshaw57** [acederberg/pydantic-settings-yaml#24]
@acederberg 

Has anyone encountered any issues with docker secrets getting injected? 
I did a small concept project in docker swarm and successfully recognized secrets and injected into object graph. 
However, for local dev/debug/tinkering I use docker-compose, not swarm. I mapped local files in (not external), accessible in the container, `secrets_dir` is set appropriately (`/run/secrets`), but none of these are resolving. secret names match `env_prefix` and `env_nested_delimiter` and also tried with annotating an alias on the properties.

I.e.
```python
class CeleryConfig(BaseCfgModel):
    broker_url: AmqpDsn = ...
    backend_url: RedisDsn = Field(..., alias="MYORG_COMPONENT__CELERY__BACKEND_URL")
    ...

class AppSettings(BaseCfgModel):
    cam: CamConfig = ...
    db: DbConfig = ...
    celery: CeleryConfig = ...

class YamlAppSettings(BaseYamlSettings, AppSettings):
    model_config = YamlSettingsConfigDict(
        extra=Extra.allow,
        env_prefix='MYORG_COMPONENT__',
        env_nested_delimiter='__',
        validate_default=True,
        case_sensitive=False,
        env_file='.env',
        env_file_encoding='utf-8',
        secrets_dir='/run/secrets',
        yaml_file_encoding='utf-8',
        yaml_files=[
            "./conf/settings.yaml",
            "./conf/settings.dev.yaml"
        ]
    )
```

```yaml
...
secrets:
  MYORG_COMPONENT__CELERY__BACKEND_URL:
    file: ${COMPOSE_SECRETS_PATH}/MYORG_COMPONENT__CELERY__BACKEND_URL
  MYORG_COMPONENT__CELERY__BROKER_URL:
    file: ${COMPOSE_SECRETS_PATH}/MYORG_COMPONENT__CELERY__BROKER_URL
...
services:
  someapi:
    ...
    environment:
      LOG_LEVEL: DEBUG
      SECRETS_DIR: /run/secrets
      YAML_SETTINGS_PYDANTIC_LOGGER: true
    secrets:
      - MYORG_COMPONENT__CELERY__BACKEND_URL
      - MYORG_COMPONENT__CELERY__BROKER_URL
      ...
```

log output does NOT complain about `SECRETS_DIR` existence, verified exists from inside container and contents are as expected
However, validation on `YamlAppSettings()` fails and reports errors for all properties where I'm expecting it to load from a secret

Have you encountered this or do you have any thoughts or suggestions?
